version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "8080:8080"
    environment:
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - "./data:/tmp/localstack"m